{
    "th07 Menu Start": "Start the game",
    "th07 Menu Extra Start": "Start the extra stage",
    "th07 Menu Practice Start": "Select a stage, and start practicing",
    "th07 Menu Result": "View score and spell card history",
    "th07 Menu Music Room": "Listen to music",
    "th07 Menu Replay": "Watch the replays",
    "th07 Menu Option": "Change the settings",
    "th07 Menu Quit": "Quit the game",
    "th07 Option Player": "Choose the initial number of lives to start with. (Default: 3)",
    "th07 Option Graphic": "Change the color depth of the screen. 32-bit looks most beautiful.",
    "th07 Option BGM": "Change the method of playing BGM. (Default: WAV)",
    "th07 Option Sound": "Choose whether to play sound effects.",
    "th07 Option Window Mode": "Switch between full screen and windowed.",
    "th07 Option Slow Mode": "Slow down when there's a lot of bullets on screen. (no high score or replay though)",
    "th07 Option Reset": "Restore settings to default.",
    "th07 Option Key Config": "Configure key controls.",
    "th07 Option Quit": "Leave settings menu.",
    "th07 Key Shot": "Set shot/confirm button.",
    "th07 Key Bomb": "Set bomb/cancel button.",
    "th07 Key Slow": "Set the slow movement button.",
    "th07 Key Skip": "Set the skip message button.",
    "th07 Key Pause": "Set the pause button.",
    "th07 Key Up": "Set the button to move up.",
    "th07 Key Down": "Set the button to move down.",
    "th07 Key Left": "Set the button to move left.",
    "th07 Key Right": "Set the button to move right",
    "th07 Key ShotSlow": "Move slower when holding down the shot key.",
    "th07 Key Reset": "Restore settings to default.",
    "th07 Key Quit": "Leave button configuration.  ",
    "th08 Option BGM Volume": "Adjust the volume of the BGM.",
    "th08 Option SE Volume": "Adjust the volume of sound effects.",
    "th09 Menu Story Start": "Start the Flower Viewing mode",
    "th09 Menu Extra Start": "Start the Extra mode",
    "th09 Menu Match Start": "Start with a PvP, vs. CPU, or watch mode",
    "th09 Menu Replay": "Playback replays",
    "th09 Menu Result": "See records",
    "th09 Menu Music Room": "Enter the music room",
    "th09 Option BGM": "Change the method of playing BGM. *MIDI isn't yet currently supported.",
    "th09 Option Key Config": "Setting the key controls",
    "th09 Key Side": "Select 1P or 2P.",
    "th09 Key Control Type": "PAD 1 or 2: use joypad; Full, Left, or Right: Use keyboard.",
    "th09 Key Charge Type": "Change the behavior of the charge button",
    "th09 Key Shot": "Set the shot button",
    "th09 Key Bomb": "Set the bomb button",
    "th09 Key Slow": "Set the low speed or the charge button",
    "th06 Bomb Reimu A": "Spirit Sign \"Fantasy Seal\"",
    "th06 Bomb Reimu B": "Dream Sign \"Evil-Sealing Circle\"",
    "th06 Bomb Marisa A": "Magic Sign \"Stardust Reverie\"",
    "th06 Bomb Marisa B": "Love Sign \"Master Spark\"",
    "th07 Bomb Reimu A unfocused": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "th07 Bomb Reimu A focused": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "th07 Bomb Reimu B focused": "Dream Sign \"Duplex Barrier\"",
    "th07 Bomb Marisa A focused": "Magic Sign \"Milky Way\"",
    "th07 Bomb Marisa B unfocused": "Love Sign \"Non-Directional Laser\"",
    "th07 Bomb Sakuya A unfocused": "Illusion Sign \"Indiscriminate\"",
    "th07 Bomb Sakuya A focused": "Illusion Sign \"Killing Doll\"",
    "th07 Bomb Sakuya B unfocused": "Time Sign \"Perfect Square\"",
    "th07 Bomb Sakuya B focused": "Time Sign \"Private Square\"",
    "th08 Bomb Reimu": "Spirit Sign \"Fantasy Orb\"",
    "th08 Bomb Reimu Last": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "th08 Bomb Yukari": "Border Sign \"Quadruple Barrier\"",
    "th08 Bomb Yukari Last": "Boundary \"Quadruple Barrier of the Imperishable Night\"",
    "th08 Bomb Marisa Last": "Magicannon \"Final Spark\"",
    "th08 Bomb Alice": "Magic Sign \"Artful Sacrifice\"",
    "th08 Bomb Alice Last": "Magipulation \"Return Inanimateness\"",
    "th08 Bomb Sakuya Last": "Buriallusion \"Phantomic Killer in Night Mist\"",
    "th08 Bomb Remilia": "Scarlet Sign \"Red the Nightless Castle\"",
    "th08 Bomb Remilia Last": "Scarlet Magic \"Scarlet Devil\"",
    "th08 Bomb Youmu": "Human Sign \"Slash of Present World\"",
    "th08 Bomb Youmu Last": "Human Oni \"Slash of the Eternal Future\"",
    "th08 Bomb Yuyuko": "Death Sign \"Ghastly Dream\"",
    "th08 Bomb Yuyuko Last": "Deadly Butterfly \"Eternal Sleep in Dreamland\"",
    "th08 Spell Dissolve": "\"Dissolve Spell\"",
    "th08 Spell Resurrection": "\"Resurrection\"",
    "th08 Music Room spoiler 1": "*** NOTE ***",
    "th08 Music Room spoiler 2": "This song hasn't been played in the game yet.",
    "th08 Music Room spoiler 3": "If you do not want to hear the song or see the comments, ",
    "th08 Music Room spoiler 4": "It is recommended that you stay away from here as soon as possible.",
    "th08 Music Room spoiler 5": "　",
    "th09 Music Room spoiler 1": "***** NOTE *****",
    "th09 Music Room spoiler 2": "This song hasn't been played in the game yet.",
    "th09 Music Room spoiler 3": "You can listen to a sample, but song titles can't be viewed.",
    "th10 Music Room spoiler 1": "<c$** Selected song has not yet been played in-game **$>",
    "th10 Music Room spoiler 2": "<c$Song comments may contain spoilers.$>",
    "th10 Music Room spoiler 3": "<c$Do you still wish to play this song?$>",
    "th10 Music Room spoiler 4": "<c$If you would like to play, please press the button again.$>",
    "th10 Music Room spoiler 5": "<c$If you do not want to play, please move the cursor.$>",
    "th13 spell nothing": "Nothing...",
    "th10 Dialog Prompt": "Please select a window mode.",
    "th10 Dialog Fullscreen": "Full screen",
    "th10 Dialog Always ask": "Always ask",
    "th11 Dialog Fullscreen 640": "Full screen (640×480)",
    "th11 Dialog Window 640": "Windowed (640×480)",
    "th11 Dialog Window 960": "Windowed (960×720)",
    "th11 Dialog Window 1280": "Windowed (1280×960)",
    "th11 Dialog Game Start": "Start",
    "th14 Dialog Prompt": "Select the resolution:",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280×960 (Recommended)",
    "th14 Dialog Fullscreen": "Play in full screen",
    "th14 Dialog Always ask": "Always ask",
    "alcostg JP": "Uwabami Breakers",
    "th128 JP": "Fairy Wars",
    "th06 config": "Touhou Koumakyou - Environment Custom Program",
    "th07 config": "Touhou Youyoumu - Environment Custom Program",
    "th08 config": "Touhou Eiyashou - Environment Custom Program",
    "th09 config": "Touhou Kaeidzuka - Environment Custom Program",
    "th095 config": "Touhou Bunkachou - Environment Custom Program",
    "th10 config": "Touhou Fuujinroku - Environment Custom Program",
    "alcostg config": "Uwabami Breakers - Environment Custom Program",
    "th11 config": "Touhou Chireiden - Environment Custom Program",
    "th12 config": "Touhou Seirensen - Environment Custom Program",
    "th125 config": "Double Spoiler - Environment Custom Program",
    "th128 config": "Fairy Wars - Environment Custom Program",
    "th13 config": "Touhou Shinreibyou - Environment Custom Program",
    "th14 config": "Touhou Kishinjou - Environment Custom Program",
    "th06 up": "Up ",
    "th06 down": "Down ",
    "th06 left": "Left ",
    "th06 right": "Right ",
    "th06 vertex": "Don't use the vertex buffer",
    "th06 fog": "Don't use fog",
    "th06 16bit textures": "16 Bit textures",
    "th06 Gouraud shading": "Suppress use of Gouraud shading",
    "th06 color composition": "Color composition isn't applied to textures",
    "th06 rasterizer mode": "Start in reference rasterizer mode",
    "th06 clear buffer": "Clear back buffer on refresh",
    "th06 minimum graphics": "Display minimum graphics needed",
    "th06 depth test": "Turn off the depth test",
    "th06 force frame": "Forcibly keep on 60 frames",
    "th06 fullscreen": "Full screen",
    "th06 windowed": "Windowed",
    "th06 full rate": "1/1 (default)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32-bit",
    "th06 16bits mode": "16-bit",
    "th06 accept": "OK",
    "th06 cancel": "Cancel",
    "th06 screen mode": "Screen mode",
    "th06 refresh rate": "Frameskip",
    "th06 colors": "Color mode",
    "th06 pad X axis": "Pad X Axis (1–1000)",
    "th06 pad Y axis": "Pad Y Axis (1–1000)",
    "th06 check pad": "Check pad input",
    "th06 DirectInput": "Don't use the DirectInput pad",
    "th06 config saved caption": "OK",
    "th06 config saved text": "Configuration saved.",
    "th07 16bits textures": "Force using 16-bit textures",
    "th07 DirectInput": "Don't use DirectInput for input control",
    "th07 BGM memory": "Preload BGM in memory",
    "th07 draw screen": "Redraw HUD every frame",
    "th07 VSync": "Disable vertical synchronization",
    "th07 fullscreen": "Full screen (Rec.)",
    "th07 low effects": "Min.",
    "th07 medium effects": "Moderate",
    "th07 high effects": "Max (Rec.)",
    "th07 32bits mode": "32-bit (default)",
    "th07 effect quality": "Effect quality",
    "th08 fog": "Disable fog (not recommended)",
    "th08 color composition": "Don't use color composition textures (forbidden)",
    "th08 depth test": "Disable depth test (not recommended)",
    "th08 rasterizer mode": "Start in reference rasterizer mode (forbidden)",
    "th08 VSync": "Disable vertical synchronization (not recommended)",
    "th09 full rate": "None (default)",
    "th09 1P controller": "1P controller",
    "th09 2P controller": "2P controller",
    "th09 gamepad 1": "Gamepad 1",
    "th09 gamepad 2": "Gamepad 2",
    "th09 all keyboard": "Complete keyboard",
    "th09 left side keyboard": "Left",
    "th09 right side keyboard": "Right",
    "th09 no save": "Exit without saving",
    "th09 save": "Save and exit",
    "th10 faith meter": "Show faith meter near the player",
    "th10 screen mode": "Screen mode",
    "th10 always ask": "Always ask",
    "th10 slowshot": "Focus when firing",
    "th11 input latency": "Input latency",
    "th11 stable input": "Stable (if the input doesn't work often)",
    "th11 normal input": "Normal (low CPU usage)",
    "th11 automatic input": "Automatic (detect fastest response) *Default",
    "th11 fast input": "Fast (if automatic doesn't work correctly)",
    "th11 input description": "Select the type of latency for accurate input response.\n\"Stable\" and \"Normal\" respond to the input from the previous frame.\n\"Automatic\" will attempt to provide the fastest response possible.\n\"Fast\" will provide similar performance to \"Automatic,\" but video may be distorted.\n*Doesn't work with frameskip settings other than \"No skip\"*",
    "th11 always ask": "Always ask at startup",
    "th11 sensitivity description": "If the directional input is slow, increase the sensitivity.\n(default: 600)",
    "th11 joypad sensitivity": "Joypad sensitivity",
    "th11 default": "Restore all defaults",
    "th143 config": "Danmaku Amanojaku - Environment Custom Program",
    "th143 Trophy Format": "\"%s\"",
    "th143 Trophy Get": "Nickname earned:",
    "th08 Music Room spoiler 6": "(Also, note that you can press the OK button here, along with the other songs,",
    "th08 Music Room spoiler 7": "to view the comment and play the theme, so be careful.)",
    "th08 Menu Spell Practice": "Practice a spell card against an opponent.",
    "th143 JP": "Impossible Spell Card",
    "th15 config": "Touhou Kanjuden - Environment Custom Program",
    "th08 Spell Practice Percentages": "Capture Rate  (Character/Overall)",
    "th08 Spell Practice Description": "Stage  Capture/Attempts/Total (()All Characters in Total)",
    "DirectInput fix": "Use DirectInput",
    "DirectInput fix, layout-dependent shot key": "Use DirectInput (Shot key: %c)",
    "th07 Stats Time Since Startup": "<tl$Time Since Start-up>  %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "<l$Total Playtime>  %.2d:%.2d:%.2d",
    "th07 Stats Total (All Characters)": "All Characters",
    "th08 Spell Practice Last Spell": "Last",
    "th07 Stats ReimuA": "Reimu Hakurei (Spirit)",
    "th07 Stats ReimuB": "Reimu Hakurei (Dream)",
    "th07 Stats MarisaA": "Marisa Kirisame (Magic)",
    "th07 Stats MarisaB": "Marisa Kirisame (Love)",
    "th07 Stats SakuyaA": "Sakuya Izayoi (Illusion)",
    "th07 Stats SakuyaB": "Sakuya Izayoi (Time)",
    "Stats Time Since Startup": "Time Since Start-up",
    "Stats Total Playtime": "Total Playtime",
    "Stats Play Count": "Play Count",
    "Stats Clear Count": "Clear Count",
    "Stats Continue": "Continues",
    "Stats Practice": "Practice",
    "Stats Retries": "Retries",
    "th16_ascii_score_at": "Fa",
    "th16_ascii_score_autumn": "Fall  ",
    "th105_profile_will_delete": " will be deleted.",
    "th105_profile_will_copy": " will be copied.",
    "th105_init_failed": "Failed to initialize",
    "th105_replay_return_to_select": "Returning to select. Save replay?",
    "th105_replay_return_to_title": "Returning to title. Save replay?",
    "th105_replay_saved": "Replay saved.",
    "th105_replay_save": "Save replay?",
    "th105_replay_delete": "Delete this replay?",
    "th105_continue": "Continue?  %d left",
    "th105_netplay_select_addr": "Please select connection",
    "th105_netplay_port": "Input port number...",
    "th105_netplay_enter_addr": "Enter connection address",
    "th105_netplay_allow_spectating": "Allow spectating?",
    "th105_netplay_await": "Waiting for connection...",
    "th105_netplay_no_spectating": "Spectating is not allowed",
    "th105_netplay_game_not_available": "Game has not started yet.",
    "th105_netplay_connection_failed": "Connection failed.",
    "th105_netplay_connecting": "Connecting...",
    "th105_netplay_connect_for_match": "Play a match? (Select no to spectate)",
    "th105_netplay_confirm_address": " is the address?",
    "th105_netplay_already_playing": "Already playing.",
    "th105_netplay_already_playing_spectate": "Already playing. Spectate?",
    "th105_delete_failed": "Removal failed.",
    "th105_delete_suceeded": "Removed.",
    "th105_profile_save_changes": "Save changes?",
    "th105_profile_deck_too_big": "A deck must have 20 cards.",
    "th105_profile_creation_failed": " creation failed.",
    "th105_profile_created": " created.",
    "th105_profile_copied": "Profile copied.",
    "th105_profile_copy_failed": "Profile copy failed.",
    "th105_profil_rename_failed": "Name change failed.",
    "th105_profil_renamed": "Name changed.",
    "th105_profile_overwrite": " can be overwritten?",
    "th123_replay_create_folder_failed": "Failed to create replay folder.",
    "th123_profile_create_folder_failed": "Failed to create profile folder.",
    "th08 Stats Reimu & Yukari": "Reimu & Yukari",
    "th08 Stats Marisa & Alice": "Marisa & Alice",
    "th08 Stats Sakuya & Remilia": "Sakuya & Remilia",
    "th08 Stats Youmu & Yuyuko": "Youmu & Yuyuko",
    "th08 Stats Reimu": "Reimu Hakurei",
    "th08 Stats Yukari": "Yukari Yakumo",
    "th08 Stats Marisa": "Marisa Kirisame",
    "th08 Stats Alice": "Alice Marigold",
    "th08 Stats Sakuya": "Sakuya Izayoi",
    "th08 Stats Remilia": "Remilia Scarlet",
    "th08 Stats Youmu": "Youmu Konpaku",
    "th08 Stats Yuyuko": "Yuyuko Saigyouji",
    "th08 Spell Practice Easy Mode": "Spell Practice (Easy)",
    "th08 Spell Practice Normal Mode": "Spell Practice (Normal)",
    "th08 Spell Practice Hard Mode": "Spell Practice (Hard)",
    "th08 Spell Practice Lunatic Mode": "Spell Practice (Lunatic)",
    "th08 Spell Practice Extra Mode": "Spell Practice (Extra)",
    "th08 Spell Practice Last Word": "Spell Practice (Last Word)",
    "th10 JP": "Mountain of Faith",
    "th11 JP": "Subterranean Animism",
    "th12 JP": "Undefined Fantastic Object",
    "th125 JP": "Double Spoiler",
    "th13 JP": "Ten Desires",
    "th14 JP": "Double Dealing Character",
    "th15 JP": "Legacy of Lunatic Kingdom",
    "th165 JP": "Violet Detector",
    "th16 config": "Touhou Tenkuushou - Environment Custom Program",
    "th165 config": "Touhou Hifuu Nightmare Diary - Environment Custom Program",
    "th07 Stats Play Count": "Play Count                        Easy Norm Hard Luna Extra Total",
    "th07 Stats Clear Count": "Clear Count  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries": "Retries  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Play Count +Phantasm": "Play Count                        Easy Norm Hard Luna Extra Phants Total",
    "th07 Stats Clear Count +Phantasm": "Clear Count  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue": "Continues  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue +Phantasm": "Continues  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice": "Practices  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice +Phantasm": "Practices  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries +Phantasm": "Retries  %6d %6d %6d %6d %6d %6d %6d",
    "th08 Spell Result Character Select": "%3d/%3d（Change Characters↓↑）",
    "th07 Spell Result Character Select": "%s  Total %3d / Got %3d (Change Characters↓↑)",
    "th07 Stats Header Total": "Total",
    "th06 Stats ReimuA": "Reimu Hakurei (Spirit)",
    "th06 Stats ReimuB": "Reimu Hakurei (Dream)",
    "th06 Stats MarisaA": "Marisa Kirisame (Magic)",
    "th06 Stats MarisaB": "Marisa Kirisame (Love)",
    "th08 Stats Total (All Characters)": "All Characters",
    "th08 Stats Time Since Startup": "<tl$Time Since Start-up>  %.2d:%.2d:%.2d",
    "th08 Stats Total Playtime": "<l$Total Playtime>  %.2d:%.2d:%.2d",
    "th08 Stats Play Count": "Play Count",
    "th08 Stats Clear Count": "Clear Count  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "Continues  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Practice": "Practices  %6d %6d %6d %6d %6d %6d",
    "th17 config": "Touhou Kikeijuu - Environment Custom Program",
    "th16 third rate": "1/3",
    "th16 half rate": "1/2",
    "th16 default": "Restore all defaults",
    "th16 Dialog Always ask": "Always ask at startup",
    "th16 sensitivity description": "If the directional input is slow, increase the sensitivity.\n(default: 600)",
    "th16 joypad sensitivity": "Joypad sensitivity",
    "th16 input description": "Select the type of latency for accurate input response.\n\"Stable\" and \"Normal\" respond to the input from the previous frame.\n\"Automatic\" will attempt to provide the fastest response possible.\n\"Fast\" will provide similar performance to \"Automatic,\" but video may be distorted.\n*Doesn't work with frameskip settings other than \"No skip\"*",
    "th16 refresh rate": "Frameskip",
    "th16 fast input": "Fast (if automatic doesn't work correctly)",
    "th16 normal input": "Normal (low CPU usage)",
    "th16 input latency": "Input latency",
    "th16 stable input": "Stable (if the input doesn't work often)",
    "th16 full rate": "None (default)",
    "th16 automatic input": "Automatic (detect fastest response) *Default",
    "th16 no save": "Exit without saving",
    "th16 slowshot": "Focus when firing",
    "th17 JP": "Wily Beast and Weakest Creature",
    "th16 JP": "Hidden Star in Four Seasons",
    "th16 Dialog Fullscreen": "Full screen",
    "th08 Spell Practice List Description": "Acquired / Challenged (Totals in main story)",
    "th08 Spell Practice Owner/Difficulty Line": "User  %s　　%s %s",
    "th08 Spell Practice Highscore Title": "Acquired/Challenged[Total Score]　%s　All characters",
    "th08 Spell Practice Comment": "Card comment",
    "th08 Spell Condition Line 2 205": "　　　　　　　Clear.",
    "th08 Spell Condition Line 1 205": "Selectable when acquired at least 7 Extra spell cards.",
    "th08 Spell Condition Line 2 206 207 209": "　　　　　　　Regardless of Difficulty.",
    "th08 Spell Condition Line 1 206": "Selectable when Normal FinalB cleared with 2 or more characters.",
    "th08 Spell Condition Line 1 207": "Selectable when Normal FinalB cleared with 3 or more characters.",
    "th08 Spell Condition Line 1 208": "Selectable when 50 spell cards acquired in spell card mode.",
    "th08 Spell Condition Line 2 208 211 217 220": "　　　　　　　All characters.",
    "th08 Spell Condition Line 1 209": "Selectable when Normal FinalB cleared with 4 or more characters.",
    "th08 Spell Condition Line 1 211": "Selectable when 15 spell cards acquired in spell card mode.",
    "th08 Spell Condition Line 2 212": "　　　　　　　and when seen Nr.%.3d at least once.",
    "th08 Spell Condition Line 1 212": "Selectable when No.%.3d,%.3d acquired",
    "th08 Spell Condition Line 1 217": "Selectable when 120 spell cards acquired in spell card mode.",
    "th08 Spell Condition Line 1 218": "Selectable when Normal FinalB cleared with 6 or more characters.",
    "th08 Spell Condition Line 1 220": "Selectable when 30 spell cards acquired in spell card mode.",
    "th08 Spell Condition Line 2 221": "　　　　　　　Characters without continues.",
    "th08 Spell Condition Line 1 221": "Selectable when Lunatic cleared.",
    "th08 Spell Condition Line 1 222": "Selectable when all Last Words seen at least once.",
    "th08 Spell Condition Line 1 219": "Selectable when Extra cleared with at least 3 characters.",
    "th08 Spell Condition Line 1 210": "Selectable when No.%.3d acquired.",
    "th08 Spell Condition Line 2 215": "　　　　　　　all Spell Cards are aquired.",
    "th08 Spell Condition Line 1 215": "Selectable when in Marisa (Solo Normal)",
    "th08 Spell Condition Line 1 216": "Selectable when Reimu (Solo Hard) or higher is cleared.",
    "th08 Spell Condition Line 2 216": "　　　　　　　Only last scene in Final B.",
    "th08 Spell Condition Line 2 213 214 222": "　　　　　　　No acquisition necessary.",
    "th08 Spell Condition Line 1 213": "Selectable when No.%.3d,%.3d,%.3d seen at least once.",
    "th08 Spell Condition Line 1 214": "Selectable when No.%.3d,%.3d,%.3d,%.3d seen at least once.",
    "th01": "Touhou Wondrous Tale ~ The Highly Responsive to Prayers",
    "megamari": "MegaMari - Marisa's Ambition",
    "nsml": "Marisa and the 6 Mushrooms - New Super Marisa Land",
    "th17 Trophy Get": "Achievement earned:",
    "th02": "Touhou Demon-Sealing Record ~ The Story of Eastern Wonderland",
    "th03": "Touhou Space Time Dream ~ Phantasmagoria of Dim. Dream",
    "th04": "Touhou Gensokyo ~ Lotus Land Story",
    "th05": "Touhou Bizarre Romantic Story ~ Mystic Square",
    "th06": "Touhou Scarlet Devil Land ~ The Embodiment of Scarlet Devil",
    "th07": "Touhou Eastern Ghostly Dream ~ Perfect Cherry Blossom",
    "th075": "Touhou Gathering Reverie ~ Immaterial and Missing Power",
    "th08": "Touhou Eternal Night Vignette ~ Imperishable Night",
    "th09": "Touhou Flower Reflecting Mound ~ Phantasmagoria of Flower View",
    "th095": "Touhou Word Flower Album ~ Shoot the Bullet",
    "th10": "Touhou Eastern Wind God Chronicles ~ Mountain of Faith",
    "alcostg": "Twilight Bar Room ~ Uwabami Breakers",
    "th105": "Touhou Eastern Scarlet Perception Heaven ~ Scarlet Weather Rhapsody",
    "th11": "Touhou Earth Spirit Palace ~ Subterranean Animism",
    "th12": "Touhou Star Lotus Ship ~ Undefined Fantastic Object",
    "th123": "Touhou Unperceiving of Natural Law ~ Chase the Enigma of the Gargantuan Guignol",
    "th125": "Double Spoiler ~ Touhou Word Flower Album",
    "th128": "Great Fairy Wars ~ Touhou Three Fairies",
    "th13": "Touhou Divine Spirit Mausoleum ~ Ten Desires",
    "th135": "Touhou Heart Elegant Tower ~ Hopeless Masquerade",
    "th14": "Touhou Shining Needle Castle ~ Double Dealing Character",
    "th143": "Danmaku Amanojaku ~ Impossible Spell Card",
    "th145": "Touhou Eastern Deep Secrets Record ~ Urban Legend in Limbo",
    "th15": "Touhou Eastern Legend of the Ultramarine Orb ~ Legacy of Lunatic Kingdom",
    "th155": "Touhou Eastern Flowers of Possession ~ Antinomy of Common Flowers",
    "th16": "Touhou Eastern Jade Scepter of the Skies ~ Hidden Star in Four Seasons",
    "th165": "Secret Sealing Nightmare Diary ~ Violet Detector",
    "th17": "Touhou Eastern Beast in Oni's Shape ~ Wily Beast and Weakest Creature",
    "marilega": "MarisaLand Legacy"
}