{
    "0": "Death Sign \"Netherworld Nightshade\" -Winter-",
    "1": "Death Sign \"Netherworld Nightshade\" -Summer-",
    "2": "Forbidden Butterfly \"Depths of the Old Hell\" -Blaze-",
    "3": "Forbidden Butterfly \"Depths of the Old Hell\" -Inferno-",
    "4": "Memory \"Birth of Saigyou Ayakashi\"",
    "5": "Memory \"Aging of Saigyou Ayakashi\"",
    "6": "Trauma \"Death of Saigyou Ayakashi\"",
    "7": "Trauma \"Resurrection of Saigyou Ayakashi\"",
    "8": "Death Sign \"Ghostly Blade\"",
    "9": "Death Sign \"Ghostly Blade\"",
    "10": "Suicide \"Bloody Burial\"",
    "11": "Suicide \"Bloody Burial\"",
    "12": "Deathly Vortex \"Spirit of the Netherworld\"",
    "13": "Deathly Vortex \"Spirit of the Netherworld\"",
    "14": "Echo Sign \"Mountain Echo\"",
    "16": "Echo Sign \"Mountain Echo Scramble\"",
    "18": "Echo Sign \"Power Resonance\"",
    "22": "Mountain Echo \"Long-Range Echo\"",
    "24": "Mountain Echo \"Amplify Echo\"",
    "26": "Great Voice \"Charged Cry\"",
    "28": "Great Voice \"Charged Yahoo!\"",
    "30": "Rainbow Sign \"Umbrella Cyclone\"",
    "32": "Recovery \"Heal By Desire\"",
    "36": "Poison Nail \"Poison Raze\"",
    "38": "Poison Nail \"Poison Murder\"",
    "40": "Desire Sign \"Saved Up Desire Spirit Invitation\"",
    "42": "Desire Spirit \"Score Desire Eater\"",
    "44": "Evil Sign \"Yǎng Xiǎoguǐ\"",
    "45": "Evil Sign \"Gūhún Yěguǐ\"",
    "47": "Demonify \"Zǒuhuǒ Rùmó\"",
    "51": "Possession \"Corpse Tóngjī\"",
    "53": "Spirit Link \"Tōnglíng Yoshika\"",
    "55": "Taoist Sign \"Tao Fetal Movement\"",
    "59": "Thunder Arrow \"Gagouji's Cyclone\"",
    "60": "Thunder Arrow \"Gagouji's Cyclone\"",
    "61": "Thunder Arrow \"Gagouji's Tornado\"",
    "62": "Heaven Sign \"Rainy Iwafune\"",
    "64": "Heaven Sign \"Ame-no-Iwafune, Ascend to Heaven\"",
    "66": "Throwing Dishes \"Mononobe's Eighty Saké Cups\"",
    "70": "Blaze Sign \"Blazing Winds of Haibutsu\"",
    "72": "Blaze Sign \"Sakurai-ji in Flames\"",
    "74": "Saint Girl \"Oomonoimi's Dinner\"",
    "78": "Honor \"Colors of Twelve Levels\"",
    "80": "Honor \"Ranks of Twelve Levels\"",
    "82": "Hermit Sign \"Taoist of the Land of the Rising Sun\"",
    "84": "Hermit Sign \"Emperor of the Land of the Rising Sun\"",
    "86": "Summon \"Royal Clan's Chaotic Dance\"",
    "90": "Secret Treasure \"Armillary Sphere of Ikaruga-dera\"",
    "93": "Secret Treasure \"Prince Shotoku's Out-of-Place Artifact\"",
    "94": "Light Sign \"Halo of the Guse Kannon\"",
    "96": "Light Sign \"Guse Flash\"",
    "98": "Discernment \"Lasers of Seventeen Articles\"",
    "100": "Divine Light \"Honor the Avoidance of Defiance\"",
    "102": "\"Falling Stars on Divine Spirit Mausoleum\"",
    "104": "\"Newborn Divine Spirits\"",
    "106": "Unknown \"Will-o'-wisps in Unknown Orbit\"",
    "107": "Unknown \"Skyfish with Unknown Shape\"",
    "108": "Unknown \"Youkai Orb of Unknown Mechanics\"",
    "109": "First Duel \"Primate Danmaku Transformation\"",
    "110": "Second Duel \"Carnivorous Danmaku Transformation\"",
    "111": "Third Duel \"Avian Danmaku Transformation\"",
    "112": "Fourth Duel \"Amphibian Danmaku Transformation\"",
    "113": "Fifth Duel \"Scrolls of Frolicking Animals\"",
    "114": "Sixth Duel \"Tanuki's Monstrous School\"",
    "115": "Seventh Duel \"Wild Deserted Island\"",
    "116": "Transformation \"Pseudo-Exorcism of the Stupid Shrine Maiden\"",
    "117": "\"Mamizou Danmaku in Ten Transformations\"",
    "118": "Raccoon Sign \"Full Moon Pompokolin\"",
    "119": "\"Curse of Yuyuko Saigyouji\"",
    "120": "Mountain Echo \"Yamabiko's Specialty Echo Demonstration\"",
    "121": "Poison Nail \"Undead Murderer\"",
    "122": "Taoist Sign \"TAO Fetal Movement ~Dao~\"",
    "123": "Vengeful Spirit \"Iruka's Thunder\"",
    "124": "Saint Girl \"Sun Goddess's Sacrifice\"",
    "125": "\"Divine Spirits' Universe\"",
    "126": "\"Wild Carpet\""
}